### ISSUE TITLE
Linked portals only working when jumping through

### ISSUE THREAD

**Issue by LogicShocker** [Lauriethefish/BetterPortals#115]
As described portals are only allowing players through when jumping. Blocks seem to go through unhindered.

**Comment by Lauriethefish** [comment]
This is almost certainly an issue with how you created the portals. You need to select the corners of the frame, as described in the wiki [here](https://github.com/Lauriethefish/BetterPortals/wiki/Creating-Custom-Portals#selecting-portals). You are most likely selecting a block too high and thus the bottom block of the portal isn't actually considered to be part of the portal by BP, and won't teleport you.
