### ISSUE TITLE
Grey Cube around portals when looking through them

### ISSUE THREAD

**Issue by GingernutsMate** [Lauriethefish/BetterPortals#116]
When looking through the portals there is a grey border that seems to be the barrier of the chunk. This happens to all 4 people on my server and I'm not sure why. 
![Screenshot 2022-01-08 002837](https://user-images.githubusercontent.com/62451792/148537696-20e58de6-1ffb-4ac6-8a02-a0a71cd086f6.jpg)

**Comment by Lauriethefish** [comment]
This is not a bug, portals have a limited view distance, the grey box marks the border of the view distance.
