### ISSUE TITLE
BetterPortals Prevents Mechanism To Turn Off Nether Portal

### ISSUE THREAD

**Issue by anselhelm** [Lauriethefish/BetterPortals#12]
Good day,

Just tried out BetterPortals 0.6.2. Unfortunately, it seems to interfere with using a redstone mechanism involving lava/water to turn off the portal.

This is the design I'm using:
https://www.youtube.com/watch?v=iALWsv6o0p0

Please could you advise if this is something that can be fixed? I'd very much love to have this plugin enabled on my server, as it's a wonderful alternative to Immersive Portals.

**Comment by Lauriethefish** [comment]
What exactly happens when you try to use that design? Does the portal not light? Does it not extinguish correctly?

**Comment by anselhelm** [comment]
Sorry for the delay. Here are two videos.

Without BetterPortals: - https://youtu.be/DuExt9Iwqrg
With BetterPortals: - https://youtu.be/Wu_u2lThQr0

**Comment by anselhelm** [comment]
List of other Spigot plugins that could potentially be conflicting:

AngelChest - https://www.spigotmc.org/resources/1-12-1-16-angelchest.60383/
BestTools - https://www.spigotmc.org/resources/1-13-1-16-besttools.81490/
Cartographer 2 - https://www.spigotmc.org/resources/cartographer-2-1-8-9-1-16-4-the-best-minimap-plugin-for-bukkit.46922/
ChestSort - https://www.spigotmc.org/resources/1-8-1-16-chestsort-api.59773/
ChopChop - https://www.spigotmc.org/resources/chopchop.86728/
ColdEnd - https://www.spigotmc.org/resources/coldend.87471/
CustomTime - https://www.spigotmc.org/resources/customtime.81364/
Drop2Inventory - https://www.spigotmc.org/resources/1-8-1-16-drop2inventory.62214/
EnhancedEnchants - https://www.spigotmc.org/resources/enhancedenchants.87089/
mineOres - https://www.spigotmc.org/resources/mineores-natural-regeneration-of-ores.81980/
NetherEnableWater - https://www.spigotmc.org/resources/netherenablewater.87476/
WildStacker - https://www.spigotmc.org/resources/%E2%9A%A1%EF%B8%8F-wildstacker-%E2%9A%A1%EF%B8%8F-spawners-entities-drops-blocks-%E2%9A%A1%EF%B8%8F-spawner-upgrades.87404/
WorldChangeScreenRemover - https://www.spigotmc.org/resources/worldchangescreenremover.54297/

**Comment by anselhelm** [comment]
Here is also a list of DataPacks (excluding ones that just contain recipes):

HotBar Reload - https://www.planetminecraft.com/data-pack/hotbar-reload/
Light Level Detector - https://www.curseforge.com/minecraft/customization/light-level-detector (please note it is for a previous version officially, but works fully with 1.16.x)
Multiplayer Sleep - https://github.com/Plagiatus/datapacks/tree/master/multiplayer_sleep
TimeTracker - https://www.planetminecraft.com/data-pack/timetracker-12-14-hour-time-in-minecraft-datapack/

**Comment by Lauriethefish** [comment]
Awaiting to see if a test build fixes the issue.

**Comment by anselhelm** [comment]
Apologies for forgetting to post this here. It *almost* works perfectly. With the latest dev build of ProtocolLib and the test build you provided, the result is as follows:

- Turn on the nether portal. Portal turns on. I can see through into the nether.
- Turn off portal. Portal turns off. However, when the water turns off the portal, the bucket is flung outwards at me. What should happen is that the bucket stays in the dispenser and the water returns to the bucket.

**Comment by Lauriethefish** [comment]
Going to close this for now. I'm struggling to figure out what causes it and there are more important issues atm.
It's strange, and shouldn't happen since BP doesn't mess with creation of portals in that way.
