### ISSUE TITLE
Add option for portals that can only be viewed from a certain side of the compass

### ISSUE THREAD

**Issue by xX-GATT-Xx** [Lauriethefish/BetterPortals#129]
**What would you like added?** 
option for portals that can only be viewed from a certain side of the compass

**Is it to solve a particular problem?**
Put the problem that you're trying to solve here. This feature request might actually be a bug in disguise.
its for testing an idea for a Tardis map using BP and the Tardis plugin

**Comment by Lauriethefish** [comment]
In my opinion this is a bit too specific a use-case to add to the plugin.
