### ISSUE TITLE
Black Concrete Spawning with linked portals

### ISSUE THREAD

**Issue by CharlieJ15420** [Lauriethefish/BetterPortals#13]
Hi,

When linking 2 portals together in the overworld, sometimes the black concrete that you see through the portals (I imagine to reduce lag especially with longer render distances) sometimes doesnt despawn when you go through the portal. This sometimes leaves huge box's of black concrete that only despawns if you reconnect

**Comment by Lauriethefish** [comment]
I am aware of this issue, it occurs due to a concurrency bug where the blocks get reset when they shouldn't be.
It will be fixed next update.

**Comment by CharlieJ15420** [comment]
That's great - thanks for the quick reply! 👍
