### ISSUE TITLE
Using Mohist to allow plugins and mods to be ran at once means that the plugin is seen as out of date for 1.16.4

### ISSUE THREAD

**Issue by Cooke1000** [Lauriethefish/BetterPortals#15]
When running Mohist for 1.16.4 it states that it is out of date and the console throws out the error [15.02 19:19:27] [Server] [ERROR] Error occurred while enabling BetterPortals v0.6.2 (Is it up to date?) However for the many other plugins I am using it is perfectly fine and has no other issues.

**Comment by Lauriethefish** [comment]
Could you send the stack trace that appears after that message, if any?

**Comment by Cooke1000** [comment]
I cannot see any stack trace whenever I load up my server, thats all it states unfortunately, sorry its not much help.

**Comment by Lauriethefish** [comment]
Hmm, this is very difficult to fix.
I have very little idea of what could cause this.

**Comment by Lauriethefish** [comment]
BetterPortals doesn't support mohist, since mohist doesn't support ProtocolLib, which is required for the plugin to run. In fact, the mohist server automatically deletes ProtocolLib JARs found in the plugins folder upon startup.
