### ISSUE TITLE
Add a command to create portals

### ISSUE THREAD

**Issue by Bluebotlabz** [Lauriethefish/BetterPortals#156]
**What would you like added?**
Would it be possible to create a command such as:
/bp createportal x y z    x y z        x y z    x y z    true|false

Which would create a portal using the specified corner coordinates
and link them with the true|false parameter making them two way or not

**Comment by Lauriethefish** [comment]
Additional parameters could include the portal name (if any), and whether to flip the directions of the origin/destination.

**Comment by Bluebotlabz** [comment]
yeah, like a command for advanced users and mapmakers/minigamemakers

that's the idea

I just don't know how difficult it would be to implement

**Comment by Lauriethefish** [comment]
Not hard, I could do it tomorrow.

**Comment by Bluebotlabz** [comment]
knowing the project codebase be like:

but yeah, that would actually be really useful

**Comment by Lauriethefish** [comment]
It could be handy for map makers definitely (ideas come to mind using command blocks/data packs to make/remove portals). In terms of minigames, bp already has a Java API for creating/removing portals they could use, so it wouldn't get as much use there. but it's still a good idea.

**Comment by Bluebotlabz** [comment]
also, an unrelated thing, but using custom datapack dimensions doesn't quite work for some reason, it displays the dimension through the portal, but walking through it doesn't work

**Comment by Lauriethefish** [comment]
Any exception in the console? if so open another issue

**Comment by Bluebotlabz** [comment]
nope

**Comment by Bluebotlabz** [comment]
I think it's just bc multiverse-core and spigot custom-dimension support is pretty bad overall

**Comment by Lauriethefish** [comment]
Hmm, might as well open another issue. I could probably find a workaround.

**Comment by Bluebotlabz** [comment]
alright

**Comment by Bluebotlabz** [comment]
also, another potentially useful idea:
add a max-ping option to the config, and if a player's ping is greater than that, the betterportal doesn't display, and instead shows normally (unless it's a custom portal, then it can display glass panes configured in the config)

**Comment by Lauriethefish** [comment]
I could do that, although it may cause some problems since minecraft's built-in ping detector is really bad (often completely wrong, e.g. I live in the UK and had 5ms ping to a server in the US the other day. That's faster than the speed of light). I'll put a warning above the option if I do add it. If you want a temporary solution, iirc there's the command `/bp toggleportalview` (might be slightly different) that players can use.

**Comment by Bluebotlabz** [comment]
ok, cool

**Comment by Bluebotlabz** [comment]
Also, just wondering, when do you think you will have the time to implement the command feature?

I don't really mind, I'm just wondering when I could use it for stuff

**Comment by Lauriethefish** [comment]
I could probably do it tomorrow afternoon.

**Comment by Bluebotlabz** [comment]
cool, thanks so much!

**Comment by Lauriethefish** [comment]
Feature added in b773741210d61b26d798c39f4220583be4105dc3, you can use it with a dev build that will shortly be available [here](https://github.com/Lauriethefish/BetterPortals/actions/runs/2720761912).

The command is `/bp createfromcoords` (type it in and press enter to get the usage). The originX1, etc... are the corners of the portal in this order:
origin corner 1
origin corner 2
destination corner 1
destination corner 2

I also added a `/bp removebyname` command for map makers (since then they can give their portals a name and remove them automatically).

@Bluebotlabz

**Comment by Bluebotlabz** [comment]
woah! just looking at the code, this looks amazing

although, I do have a question:

in the code:
~~~

**Comment by Bluebotlabz** [comment]
wait, I didn't read the code properlly, and I didn't realise that twoway and dual are the same...

also, I'm guessing invert makes the portal throw you out facing the oposite direction

**Comment by Bluebotlabz** [comment]
@Lauriethefish I have found a small bug:
Relative coordinates don't work

Also, I was wondering if autocomplete could be added for the coordinates like the minecraft setblock command does (autofill the block the player is looking at)?

**Comment by Bluebotlabz** [comment]
I think it's due to the fact that the code sets the selection coords directly:
~~~java
        IPortalSelection selection = selectionProvider.get();
        selection.setPositionA(new Location(world, x1, y1, z1));
        selection.setPositionB(new Location(world, x2, y2, z2));
~~~

**Comment by Bluebotlabz** [comment]
Another minor bug:
The remove command only removes one portal, but not the one that it is linked to

**Comment by Bluebotlabz** [comment]
I should also probably mention that implementing caret notation local coordinates would also be useful

**Comment by Lauriethefish** [comment]
> also I think that the remove command should also remove the linked origin/destination portal
`/bp remove` *does* do this already, unless you explicitly tell it not to with `/bp remove false`. 
I think the issue you might have been having is that Java parses any string other than `"true"` as being `false`, so when you did `/bp remove someName`, the plugin interpreted that as `/bp remove false` and didn't remove the linked portal.

**Comment by Lauriethefish** [comment]
As for carat notation, I will open a separate issue.

**Comment by Bluebotlabz** [comment]
> As for carat notation, I will open a separate issue.

haha, me doing my best with copying, pasting, VSCode and hacky Java go brrrrrr

Yes, I know Eclipse exists, but....

**Comment by Lauriethefish** [comment]
Sorry, still missing some stuff.

> also, I'm guessing invert makes the portal throw you out facing the oposite direction
Yep, correct.

> Also, I was wondering if autocomplete could be added for the coordinates like the minecraft setblock command does (autofill the block the player is looking at)?
I would do this, however my current command system is pretty bad, so this would require a lot of changes to implement. Perhaps it could happen in the future.

It's important to note that if you're using these commands to add/remove portals on the fly, it might be easier to do that will permissions instead. If you named the portal `myPortal`, then the permissions `betterportals.see.custom.myPortal` and `betterportals.use.custom.myPortal` will be checked before seeing or teleporting through the portal (respectively). You could use commands to add/remove these permissions.

**Comment by Lauriethefish** [comment]
BTW, by carat notation do you mean coordinates like `~5` (just want to clarify because that's a tilde, not a carat)

**Comment by Bluebotlabz** [comment]
> I would do this, however my current command system is pretty bad, so this would require a lot of changes to implement. Perhaps it could happen in the future.

I'm about to make it worse lol


> It's important to note that if you're using these commands to add/remove portals on the fly, it might be easier to do that will permissions instead. If you named the portal myPortal, then the permissions betterportals.see.custom.myPortal and betterportals.use.custom.myPortal will be checked before seeing or teleporting through the portal (respectively). You could use commands to add/remove these permissions.

That only works for static portals, I'm making some crazy timetravel TVA kinda stuff, so I need portals that can spawn relative to the player (hence my trash fork)

Here's a sneak peek:
![image](https://user-images.githubusercontent.com/69104218/180567429-aa713d0f-2149-4ff9-88ed-46ee4c7044e3.png)

**Comment by Bluebotlabz** [comment]
> BTW, by carat notation do you mean coordinates like `~5` (just want to clarify because that's a tilde, not a carat)

carats:
https://minecraft.fandom.com/wiki/Coordinates#Relative_world_coordinates

**Comment by Lauriethefish** [comment]
ooo I hadn't heard of any of that. I'm interested to see what you come up with.

**Comment by Lauriethefish** [comment]
Separate issue created. Going to close this one for now since the command is implemented and works.
