### ISSUE TITLE
Support for Relative Coordinate Notation in Commands

### ISSUE THREAD

**Issue by Lauriethefish** [Lauriethefish/BetterPortals#157]
**What would you like added?**
Support for the relative coordinate notation described [here](https://minecraft.fandom.com/wiki/Coordinates#Relative_world_coordinates) in commands.
**Is it to solve a particular problem?**
I'm sure that @BlueBotLabz can fill this in later.

**Comment by Bluebotlabz** [comment]
It solves doing black-magic with commands and BetterPortals lol

**Comment by Lauriethefish** [comment]
pretty much.

**Comment by Bluebotlabz** [comment]
I've added a basic implementation and submitted a pull request (it also has one or two other bugfixes)

Also, I'm going to try to implement command autocomplete or hints for the createportal command later

**Comment by Lauriethefish** [comment]
Solved in #158
