### ISSUE TITLE
Turning on nether portals

### ISSUE THREAD

**Issue by Nymelez** [Lauriethefish/BetterPortals#18]
I have downloaded the plugin and learned how to use custom portals but is there just a way to light on a portal like in vanilla and it shows the other side, because if there is I haven't found it

**Comment by Lauriethefish** [comment]
To light the portal with flint and steel is all that's needed.

**Comment by Nymelez** [comment]
Well I have tried that but it doesn't light up

**Comment by Lauriethefish** [comment]
Wait about 10 seconds, portals sometimes take a while to light.

**Comment by Nymelez** [comment]
The fire goes out before the portal even lights up

**Comment by Lauriethefish** [comment]
Is there any "An invalid world connection was found" upon starting up your server?

**Comment by Lauriethefish** [comment]
Closed due to inactivity.
I know what this issue is caused by, and it isn't a problem on my end, so issues isn't really the place.
You need to modify the config file with your world name, instead of the default `world` and `world_nether`, then run `/bp reload`.
