### ISSUE TITLE
Hex color support in messages.

### ISSUE THREAD

**Issue by AZFire1** [Lauriethefish/BetterPortals#27]
**What would you like added?**
Add the somewhat new 1.16 hex support to be used in plugin messages. Preferably, could you have it work as {(hex)} rather than anything else like &(hex) or just the (hex) as most plugins do it this way.

**Is it to solve a particular problem?**
I suppose, my color scheme heavily utilizes hex so I'd need BP to have support for it when I customize it.

**Comment by Lauriethefish** [comment]
See this pull request: https://github.com/Lauriethefish/BetterPortals/pulls/32

**Comment by Lauriethefish** [comment]
Now has been added.
