### ISSUE TITLE
Players riding entities don't show through portals

### ISSUE THREAD

**Issue by XoToM** [Lauriethefish/BetterPortals#3]
Literally what it says above. 
The player will appear as standing/flying above the entity its supposed to ride instead of sitting on it.

**Comment by Lauriethefish** [comment]
Which versions does this happen on?

**Comment by XoToM** [comment]
I found out about it on 1.16.2, however it might also happen on earlier versiosn

**Comment by Lauriethefish** [comment]
Fixed. For now you can download a version with the fix from actions, but it isn't uploaded to spigot yet.
