### ISSUE TITLE
Server crash at high coords

### ISSUE THREAD

**Issue by soshimee** [Lauriethefish/BetterPortals#31]
**Describe the bug**
What is going wrong? Does the plugin crash? What have you tried to try and fix the problem, if anything.
The entire server crashes when a player makes a portal at high coords.

**To Reproduce**
How would I make this bug happen in order to fix it?
Just go extremely far from spawn (like x 99999999 z 999999) then make a portal, server will crash.

**Server Logs**
Please enable debug logging by setting `logLevel` in the config file to `FINER`, then running `/bp reload`. Try to reproduce your issue, then send your full server log here.
https://mclo.gs/nr9rlnh

If you can't do this for security reasons, an excerpt of log will probably suffice.

**Additional context**
Any other info.
I can't even make my server work anymore...

**Comment by Lauriethefish** [comment]
Possibly a hidden floating point precision error, I'll look into this.

**Comment by Lauriethefish** [comment]
If you need your server to work, just remove BetterPortals, or delete `portals.yml` and turn it back on.

**Comment by soshimee** [comment]
I’ll remove it for now

**Comment by Lauriethefish** [comment]
Progress: I've managed to fix the bug locally, however some of the block positions are incorrect, even with the fix applied.
I'm working on a full fix, but it's possible that this will be very difficult.

**Comment by Lauriethefish** [comment]
That commit fixes the issue.
A build with the fix is available for download via [github actions](https://github.com/Lauriethefish/BetterPortals/actions/runs/670811814). Click `artifact` and then you'll find the build within the ZIP.

**Comment by Lauriethefish** [comment]
I'd appreciate it if you could reply @soshimee, this is quite a serious issue.

**Comment by soshimee** [comment]
Yes, a reply.

**Comment by Lauriethefish** [comment]
Did it fix the issue?

**Comment by soshimee** [comment]
It did.
