### ISSUE TITLE
Interact through portals

### ISSUE THREAD

**Issue by soshimee** [Lauriethefish/BetterPortals#33]
**What would you like added?**
Interaction with portals through blocks, like opening a door. I would also appreciate if you make the area beyond the portal actually loaded (so animals and stuff don't look unnatural through portals staying in one place).

**Is it to solve a particular problem?**
When interacting with blocks beyond portals that has portal blocks off, the portal blocks appear then disappear. And I want to be able to open the door right in front of the portal that is very hard to interact with right now.

**Comment by Lauriethefish** [comment]
The area at the destination of portals *is* force loaded, however entities don't really move unless there are players nearby, so thats' why they look unnatural.

Interacting with blocks through portals is something that is very difficult to implement properly without a lot of NMS and a lot of compatibility issues with existing plugins. I'm sure you can see that a lot of plugins would complain if we suddenly used NMS to allow interactions with entities from a completely separate world.

This is why it isn't implemented, and to be honest, it's not something that I'm interested in adding any time soon.
For now I'm going to close this, and perhaps explore more options in the future.
