### ISSUE TITLE
Java 16 Problem

### ISSUE THREAD

**Issue by Teals53** [Lauriethefish/BetterPortals#35]
Plugin crashes on Java 16.

A link to the crash is [here](https://paste.md-5.net/iramevodok.cs)

**Comment by kacperleague9** [comment]
Why do you use java 16? do you really need it

**Comment by Teals53** [comment]
yes its latest and i just prepared my server for 1.17 its required too xd

**Comment by Teals53** [comment]
im using around 60 plugin and this is the only plugin i cannot use in java 16 so im glad if u can fix that

**Comment by kacperleague9** [comment]
1.17 will require java 11 at least

**Comment by Teals53** [comment]
i decided to install the latest version when i updated it, did i do bad ? xd

**Comment by Lauriethefish** [comment]
This is an issue with google guice (the dependency injection framework I use), and sadly isn't something that I can fix directly.
I hope that guice 5.0 fixes it

**Comment by kacperleague9** [comment]
i recommend you to use java 11

**Comment by Teals53** [comment]
kk

**Comment by Lauriethefish** [comment]
For now I'm closing this, because it's not something that I can fix directly.
Hopefully guice 5.0 releases soon and fixes this.

**Comment by Teals53** [comment]
kk

**Comment by Lauriethefish** [comment]
Fixed in guice 5.0, releasing update soon.
