### ISSUE TITLE
Mobs sometimes spawn in portal frame when pushed through, and thus suffocate

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [Lauriethefish/BetterPortals#36]
if a portal with a width of 2 blocks is built (default), then the mobs that we push into the portal appear on the other side right in the frame of the portal and die. that is, the plugin will incorrectly spawn mobs on the other side. we also noticed that the portals do not correctly copy the suits of horses.

**Comment by KairuByte** [comment]
May want to break off horse armor into a separate issues. It’s usually best to keep each issue focused on one topic, for ease of tracking.

**Comment by Lauriethefish** [comment]
Probably caused by a fix for another issue (players spawning on top of portals). Will look into that fix to see why this is happening.

**Comment by Lauriethefish** [comment]
While I'm here, can I have your game version?

**Comment by Lauriethefish** [comment]
Horse armor also works fine through portals to me, so I need your game version.

**Comment by Envel-Nikita-Gutsenkov** [comment]
I didn't mean "Horse armor", I meant the color scheme of the horses.
spigot/paper 1.16.5

the problem with animals getting stuck is observed in 60% of cases, so we only have 40% of animals surviving. this applies to all animals: parrots, pandas, horses, etc. There is no problem if the animal enters exactly in the center of the portal

**Comment by Lauriethefish** [comment]
Weird, I can't reproduce that.
Colour schemes are gonna be difficult to fix, probably some entity metadata issue.

**Comment by Lauriethefish** [comment]
Think I've managed to reproduce it, I'll try to find a fix.

**Comment by Lauriethefish** [comment]
Cannot reproduce this issue on latest.
Horse colour schemes also appear to be correct when viewed through a portal upon latest.
