### ISSUE TITLE
Minecarts rotated incorrectly through portals

### ISSUE THREAD

**Issue by ayunami2000** [Lauriethefish/BetterPortals#39]
**Describe the bug**
What is going wrong? Does the plugin crash? What have you tried to try and fix the problem, if anything.
minecarts rotated in some situations
**To Reproduce**
How would I make this bug happen in order to fix it?
put a minecart off of tracks and turn it by pushing it. then view it through a portal on the other axis (e.g. one is on the X axis and the other is on the Z axis). it also occurs the other way around: minecarts going through the portal will end up rotated sideways.
![2021-04-30_10 22 21](https://user-images.githubusercontent.com/24785136/116708730-fdec1800-a99d-11eb-9809-ff1dae476751.png)
![2021-04-30_10 22 23](https://user-images.githubusercontent.com/24785136/116708731-ff1d4500-a99d-11eb-9690-6bada544f364.png)

**Server Logs**
Please enable debug logging by setting `logLevel` in the config file to `FINER`, then running `/bp reload`. Try to reproduce your issue, then send your full server log here.
not relevant this is probably just the fact that minecart rotation is weird
If you can't do this for security reasons, an excerpt of log will probably suffice.

**Additional context**
Any other info.

**Comment by Lauriethefish** [comment]
I am aware of this bug. It is very strange, and I don't know what exactly causes it.

I have been looking for a fix for quite a while, without much luck sadly.

**Comment by ayunami2000** [comment]
I think it's due to how minecarts work. Try switching the X and Z axis or
maybe even the Y axis specifically for minecarts when going through these
types of portals and see what happens.

**Comment by Lauriethefish** [comment]
Perhaps I will give that a go. I can't work on BP much atm, so it will be a while.

**Comment by ayunami2000** [comment]
Holy shit the plugin lives
