### ISSUE TITLE
Unlightable Portals

### ISSUE THREAD

**Issue by NerdRot** [Lauriethefish/BetterPortals#40]
**Describe the bug**
Plugins tells me to relight the portal to see through it, so I break the portal, fix it and attempt to relight. Fire is placed and no portal spawns. Appears to be like this for all size portals

**To Reproduce**
1.16.5 spigot server, repeat above.

**Server Logs**
Not sure how to do that

If you can't do this for security reasons, an excerpt of log will probably suffice.

**Comment by Lauriethefish** [comment]
Hello, this issue isn't usually one with the plugin, and is instead caused by you not having the correct world links set up in your config.
If your worlds are not called `world` and `world_nether`, you need to modify the `worldConnections` section of the config to set them up properly.

**Comment by NerdRot** [comment]
Awesome that sorted it :)
I'm having another issue, should I make another bug report so anyone else having the issue can find it easily?

**Comment by Lauriethefish** [comment]
Yep, best to keep everything to its own issue.
