### ISSUE TITLE
TeleportCooldown Not working

### ISSUE THREAD

**Issue by NerdRot** [Lauriethefish/BetterPortals#41]
**Describe the bug**
I have a portal that is against a wall, and if accessed into the side facing the wall, I cannot enter through to the other side, as it just teleports me back through when I try to move.
I assumed the TeleportCooldown would fix this, but I have tried setting it to 10, 100, and 10000 with no change.

**To Reproduce**
Walk into a one sided portal

**Server Logs**
NA

If you can't do this for security reasons, an excerpt of log will probably suffice.

**Additional context**
Any other info.

**Comment by Lauriethefish** [comment]
Teleport cooldown has been removed since version `0.7.0`.

**Comment by Lauriethefish** [comment]
I have however, just noticed that I left it in the config accidentally, which will be fixed.

**Comment by NerdRot** [comment]
Ah okay dokeys is there any other way around this that comes to mind? maybe I could flip the coordinates somehow?

**Comment by Lauriethefish** [comment]
Not exactly sure what you mean by "accessed into the side facing the wall" - could you post a video to clarify?

**Comment by NerdRot** [comment]
Basically it can only be accessed from one side, which is unfortunately the wrong side

https://user-images.githubusercontent.com/85271335/120597806-69158800-c43d-11eb-954c-faf5dbc6725f.mp4

**Comment by Lauriethefish** [comment]
Oh, I see more what you mean now.
BP doesn't support having both sides of a portal's entrance come out on the same side.
It's extremely difficult to implement without major refactoring unfortunately.

**Comment by NerdRot** [comment]
ah dangit okay dokeys
Thanks for the help anyways :)

**Comment by Lauriethefish** [comment]
np :)
