### ISSUE TITLE
Not detecting plugin or Jar file

### ISSUE THREAD

**Issue by LagoonYt** [Lauriethefish/BetterPortals#43]
It does not run the plugin or detect the jar is there. The jar is there but it does not create anything and the jar is unable to run manually or automatically.

**To Reproduce**
not sure

**Server Logs**
does not detect the plugin is there

**Additional context**
Plugin Version: 0.8.1
Game Version: 1.16.5

**Comment by Lauriethefish** [comment]
Do you have ProtocolLib installed?

**Comment by LagoonYt** [comment]
> Do you have ProtocolLib installed?

no! I'm guessing I need it

**Comment by Lauriethefish** [comment]
You do, correct.
Install it, then restart your server.

**Comment by LagoonYt** [comment]
> You do, correct.
> Install it, then restart your server.

ok thank you sorry for being stupid

**Comment by Lauriethefish** [comment]
np, dw

**Comment by LagoonYt** [comment]
> np, dw

yes it has fixed it thank you very much
