### ISSUE TITLE
BetterPortals not working

### ISSUE THREAD

**Issue by Corbinator333** [Lauriethefish/BetterPortals#45]
**Describe the bug**
When I log into my server, it says this: "**[ProtocolLib] Loaded class {0} from {1} which is not a depend, soft depend, or loadbefore of this plugin.**"

**To Reproduce**
We just have ProtocolLib and BetterPortals with Spigot 1.17

**Server Logs**
I am unable to grab them as when I try to run a /bp command it does [this](https://cdn.discordapp.com/attachments/793969913147949056/860631491842146314/unknown.png)

**Additional context**
BP Version: v0.8.1
ProtocolLib Version: [Latest Dev Build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)
Game Version: 1.17
[Screenshot of the Chatbox](https://cdn.discordapp.com/attachments/793969913147949056/860631221779300442/unknown.png)

**Comment by KairuByte** [comment]
That isn't a BP message, and isn't actually even an error, it's more info than anything.

Make sure you've updated to the latest everything. If you're on 1.17 you need to use the latest asset produced by GitHub actions.

**Comment by Corbinator333** [comment]
> That isn't a BP message, and isn't actually even an error, it's more info than anything.
> 
> Make sure you've updated to the latest everything. If you're on 1.17 you need to use the latest asset produced by GitHub actions.

I am running the latest ProtocolLib Dev build and the latest BP version from the github.

**Comment by KairuByte** [comment]
GitHub actions, not the release page. I'm on mobile, so can't link it. But it's along the top, select the latest guild, and then bearish the middle is a link to the artifact created.

**Comment by Corbinator333** [comment]
> GitHub actions, not the release page. I'm on mobile, so can't link it. But it's along the top, select the latest build, and then bearish the middle is a link to the artifact created.

This worked! Thank you so much!
