### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [Lauriethefish/BetterPortals#46]
Please add support for minecraft version 1.17.

**Comment by Lauriethefish** [comment]
Implementing 1.17 support is in progress.

**Comment by XTeamXeno** [comment]
:)

**Comment by Envel-Nikita-Gutsenkov** [comment]
up
`[23:04:33 WARN]: [BetterPortals] Task #1420 for BetterPortals v0.8.1 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.lauriethefish.betterportals.bukkit.util.nms.BlockDataUtil
	at com.lauriethefish.betterportals.bukkit.block.FloodFillViewableBlockArray.searchFromBlock(FloodFillViewableBlockArray.java:135) ~[?:?]`

**Comment by Lauriethefish** [comment]
BP has released for 1.17
