### ISSUE TITLE
Player Tracking Entity

### ISSUE THREAD

**Issue by Modog500000** [Lauriethefish/BetterPortals#65]
**Describe the bug**
What is going wrong? Does the plugin crash? What have you tried to try and fix the problem, if anything.
The plugin crashes 
**To Reproduce**
How would I make this bug happen in order to fix it?
just look through the portal for a bit and it crashes
**Server Logs**
Please enable debug logging by setting `logLevel` in the config file to `FINER`, then running `/bp reload`. Try to reproduce your issue, then send your full server log here.
https://mcpaste.io/54a99d866d5dd809
If you can't do this for security reasons, an excerpt of log will probably suffice.

**Additional context**
Plugin Version: 0.9.0
Game Version: 1.17.1 Paper

**Comment by Lauriethefish** [comment]
This issue is caused by outdated ProtocolLib.
