### ISSUE TITLE
can throw items from creative server through into none creative areas

### ISSUE THREAD

**Issue by regtable** [Lauriethefish/BetterPortals#66]
**Describe the bug**
no crash no error. im using paper mc minecraft version 1.17 better portals multiverse and multiverse inventory

**To Reproduce**
install the plugins as above for 1.17 make a portal in world then link to a portal in nether world throw items through reap rewards even though multi inv does its job to stop items moving borders.

**Server Logs**
i have no log as console throws no exceptions or errors

**Additional context**
i have seen the conf for entitys maybe if i disable that it stops the items crossing but i guess mobs too. id like mobs to travel but not thrown items any help is apreciated.

**Comment by regtable** [comment]
i just tested it with entitys off and mobs dont go through. when you throw an item through it vanishes (as expected) but when you pass through the items there on the floor waiting for you still

**Comment by Lauriethefish** [comment]
The entity toggle isn't publicly releases yet

**Comment by regtable** [comment]
Strange it is in the config I have. It makes it so it does not show
entity’s the other side of the dimension but you can see the entity’s
behind it on your side. Does odd things. I have a work around using an
inventory clearing island between areas a central hub so to speak. Love the
mod btw. I did use. 0.3 on 1.12.2 (sky factory 4) last didn’t like the
particles glad it’s gone now however it’s not a seamless load any more
assuming due to not loaded chunks or maybe Minangkabau mechanics changed?

**Comment by Lauriethefish** [comment]
Can you tell me exactly which config option you mean?

**Comment by regtable** [comment]
entitySupportEnabled = config.getBoolean("enableEntitySupport");
37
<https://github.com/Lauriethefish/BetterPortals/blob/b9b1a28dcad0bd068063386fe253a50ab0ab78d5/bukkit/src/main/java/com/lauriethefish/betterportals/bukkit/config/MiscConfig.java#L37>This
is the part of code that relates to the config option I see in the conf on
my server I’m away at work right now so can’t show fully

**Comment by regtable** [comment]
I will make a video when I am home showing what I mean

**Comment by Lauriethefish** [comment]
That option is nothing to do with entity teleportation. It is to do with whether or not you can *view* entities through a portal (including players)

**Comment by regtable** [comment]
Ahhh makes sense then I thought it was to support movement of them. So
stopping them aka loose items support coming soon?
 Thanks for taking time to help.  Sorry to be a pain

**Comment by Lauriethefish** [comment]
At the moment there's a build in testing that supports toggling whether or not non-player entities can travel through portals. I may make it a more general feature, with an entity whitelist or blacklist soon.

**Comment by regtable** [comment]
Awesome, thanks!
Be good to stop loose items not in inventory and keep mobs going through….
Maybe a per portal configuration to stop certain mobs or items like a
hopper sorter would be cool but I guess very hard.

**Comment by Lauriethefish** [comment]
Closing for now.
