### ISSUE TITLE
Entities left after removing portals

### ISSUE THREAD

**Issue by Qhurro** [Lauriethefish/BetterPortals#68]
**Describe the bug**
Whenever i remove a portal a weird entity is left behind in the frame that prevents me from building in it, removing it, or moving through it.

**To Reproduce**
Make a portal and then do /bp delete and see the entity.

**Server Logs**
Please enable debug logging by setting `logLevel` in the config file to `FINER`, then running `/bp reload`. Try to reproduce your issue, then send your full server log here.

If you can't do this for security reasons, an excerpt of log will probably suffice.

**Additional context**
Plugin Version: 0.9.0
Game Version: 1.16.5

**Comment by Lauriethefish** [comment]
I have had many reports of entities that are left behind, however I have never been able to reproduce this myself. If you have a way to reproduce this consistently, let me know and I can reopen this issue.

**Comment by Qhurro** [comment]
We had this issue many times. I will give you our setup and the exact way it was reproduced.

1. Using a free minehut server host
2. Installing Better Portals and ProtocolLib with the built in plugin installer
3. Setting up **2** 3 by 3 portal frames (3 by 3 portal size and 5 by 5 exterior frame)
4. Using portal wand to set destination and origin on the portals
5. Testing the portals for function
6. Doing /bp remove and seeing the entity left in both now empty portal frames
