### ISSUE TITLE
BetterPortals error

### ISSUE THREAD

**Issue by yohanesburg** [Lauriethefish/BetterPortals#69]
**Describe the bug**
What is going wrong? Does the plugin crash? What have you tried to try and fix the problem, if anything.

I have installed the BetterPortals plugin to my PaperMC world.  Anytime I try to light a portal I get a error message.

"You must select both sides of a portal first. For info, run /bp help"
"Unfortunately, this portal will not be lit since the world that you are in is not linked, (If you have changed the name of your world in server.properties, you need to change it in the config) If you believe this to be a mistake, contact an admin.

Any help would be greatly appreciated.

**Additional context**
Plugin Version:  0.9.0
Game Version:  1.17.1

**Comment by Lauriethefish** [comment]
This is not a bug - please ask support in discord only.
