### ISSUE TITLE
Minecarts not teleporting through portals correctly.

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [Lauriethefish/BetterPortals#8]
hi, the carts can't pass through the portal properly

[11:20:05 WARN]: Wrong location! (-2, 4) should be (-2, 0), EntityMinecartFurnace['Minecart with Furnace'/28302, uuid='e036ed17-7ff9-45b4-b310-ca568bdcff15', l='ServerLevel[world]', x=-28.80, y=150.00, z=68.00, cx=-2, cz=4, tl=1, v=true, d=false]

**Comment by Lauriethefish** [comment]
Hi, could I ask you to enable debug logging and then reproduce this bug. Then send your full server log ideally, thanks!

**Comment by ErythroCraft** [comment]
Hi

I think Envel-Nikita-Gutsenkov is meening this.

![2021-02-01_22 24 18](https://user-images.githubusercontent.com/76217862/106520066-801e8a80-64dc-11eb-8820-e0d6c4f204ea.png)


![2021-02-01_22 24 54](https://user-images.githubusercontent.com/76217862/106520082-844aa800-64dc-11eb-88f3-90403d5073f3.png)


The blocks in portals are duplicates, too. But the first duplicated block must behind the portals as self as nether portals.

**Comment by Lauriethefish** [comment]
I see the issue, it will be fixed next update.

**Comment by ErythroCraft** [comment]
THX

**Comment by Lauriethefish** [comment]
Rewrite has fixed this, hopefully should be downloadable soon.

**Comment by Lauriethefish** [comment]
Fixed in rewrite.

**Comment by ErythroCraft** [comment]
Now you can do this for player, too?
