### ISSUE TITLE
Wrong Fence Rotation Through Portals

### ISSUE THREAD

**Issue by BookWyrm114** [Lauriethefish/BetterPortals#81]
![2021-10-14_13 44 57](https://user-images.githubusercontent.com/79489385/137369440-5696a65f-9e87-4507-8071-cd7b2f03294c.png)

**Comment by rght925h** [comment]
Can confirm. Reproducible with BetterPortals 0.10.2.

**Comment by Lauriethefish** [comment]
Reproduced successfully
