### ISSUE TITLE
Portals not saving correctly

### ISSUE THREAD

**Issue by ErythroCraft** [Lauriethefish/BetterPortals#9]
Hi

I am using your plugin on my server Bukkit/Spigot 1.16.5

First issue is that the plugin is not saving created portals.
There is no message in console for this bug.

The file portals.yml is everytime emty.

**Comment by Lauriethefish** [comment]
Hello, could you enable debug logging and tell me what it says in the console whenever shutting down your server or running /bp reload?
This is in the config file.

**Comment by ErythroCraft** [comment]
Here is the latest debug.

[debug-report-2021-01-28_18.55.25.zip](https://github.com/Lauriethefish/BetterPortals/files/5889963/debug-report-2021-01-28_18.55.25.zip)

**Comment by Lauriethefish** [comment]
That's, a client debug report I think?
When referring to debug, I'm talking about the plugins debug logging feature. Please enable that in `config.yml` and run /bp reload to enable it, then send me your server log.

What server software are you using?

**Comment by ErythroCraft** [comment]
RE: What server software are you using?

Apache, Java 8+11 mixing with Spigot/Bukkit + xampp

**Comment by Lauriethefish** [comment]
Hmm, these are very strange bugs, mostly because they don't happen to me, I hope I can find the issue but it's possible I won't be able to.

**Comment by ErythroCraft** [comment]
RE: That's, a client debug report I think?

https://www.spigotmc.org/go/timings?url=ulukeminex

[debug-report-2021-01-28_22.13.49.zip](https://github.com/Lauriethefish/BetterPortals/files/5890026/debug-report-2021-01-28_22.13.49.zip)

**Comment by ErythroCraft** [comment]
> Hmm, these are very strange bugs, mostly because they don't happen to me, I hope I can find the issue but it's possible I won't be able to.

I hope

**Comment by Lauriethefish** [comment]
I have to sleep now, I will have more of a look in the morning.

**Comment by ErythroCraft** [comment]
Have time, I can wait.

syt

**Comment by ErythroCraft** [comment]
Hello

I've been testing for a while now by installing and reinstalling my plugins.

First I noticed that the plugin does not save the portals directly. Therefore, the server must be restarted after creating portals.

I noticed this by opening the portals.yml after creating it. It wasn't until I stopped the server that the file was updated.

I also use the minpacks plugin, which also has the shortcut / bp to open the backpack.

The following approach would be ideal.

1. / bportal wall
2. linking with the wall
3. / bportal create [name]
(to create first, second,... portals)
4. / bportal link [name] dest [name]

If you can do this so, you can create the plugin for four sizes with
5. / bportal [name] origin [N or S] or [E or W] dest [name] origin [N or S] or [E or W]

So I meen, one ortal has got two origins N <-> S or E <-> W and could therefore be linked from every page.

I have now been able to accelerate the performance and render with the Fast Chunk Pregenerator plugin. There are still small errors, but this is not due to your plugin.

If you want to roll up the plugin from the beginning anyway, you can think about it.

**Comment by Lauriethefish** [comment]
Ah, yeah it doesn't save them straight away. This is done for performance mostly - saving isn't super cheap so I don't want to do it too often. Running /bp reload does save you portals however.

Not sure what I could do about that /bp collision, perhaps send a build of the plugin with that changed?

**Comment by ErythroCraft** [comment]
Nice.

With the [ /betterportals reload ] command the portals will save. That is it.
The /bp command is not important, because MinePacks has got an rightClickEvent.

The /bp collision I have only on my completed server build with over 60 plugins.
That will be due to the permissions or loader, I think. 

e.g
For an command structure I'll open an new issue. 
You can think about whether you want to change the structure.
